### ISSUE TITLE
After flashing the screen is just white when plugged in and nothing happens

### ISSUE THREAD

**Issue by TheBiemGamer** [NicoAICP/PTPE#1]

**Comment by NicoAICP** [comment]
Could you send an image how you connected the things?

Also if you wanna do skylander emulation, please use kaos for now since PTPE is still unfinished

**Comment by TheBiemGamer** [comment]
Ok I'll switch to kaos I think then thx

**Comment by TheBiemGamer** [comment]
And this is how it's connected
![IMG_3986](https://user-images.githubusercontent.com/47662596/226214458-80b27586-4e7a-4417-aee3-33870425f596.jpg)

**Comment by Maceika** [comment]
Yo @NicoAICP i wanted to ask if you could join our discord server? we are building the skylander micro-computer there and we would really appreciate your help, here is the link: https://discord.gg/UWCytpJz (edit: the person who made this post, its his discord server so that you could help him out)

**Comment by NicoAICP** [comment]
> And this is how it's connected ![IMG_3986](https://user-images.githubusercontent.com/47662596/226214458-80b27586-4e7a-4417-aee3-33870425f596.jpg)

i cant see anything wrong right now, should work. You selfcompiled it yeah? try the prerelease for hardware test and tell me if it worked

**Comment by TheBiemGamer** [comment]
Yeah I compiled it myself and I got a white screen but with the hardware test it works fine I probably made an error compiling.
![IMG_3994](https://user-images.githubusercontent.com/47662596/226451834-9ce0b660-5192-48dc-8e7c-f7074918c1fa.jpg)

**Comment by NicoAICP** [comment]
If you want to ever recompile it, i ported ptpe to sdk v1.5, you can compile it using windows.
Here is the windows installer: https://github.com/raspberrypi/pico-setup-windows/releases/latest/download/pico-setup-windows-x64-standalone.exe

And here the link for the sdk1.5 branch: https://github.com/NicoAICP/PTPE/tree/sdk15

**Comment by NicoAICP** [comment]
Oh yeah dont use windows, that shit wont work tinyusb doesnt compile correctly (will still boot tho)

**Comment by leahanderson1** [comment]
got whitescreen while compiling on linux with the 2350 branch, what did i do wrong 😭
